spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/spadb
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hiberante.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-plataform=org.hibernae.dialect.MySQLDialect 

server.port=8080